### ISSUE TITLE
Remove the calculation of the reference potential energy in 3D

### ISSUE THREAD

**Issue by matt-frey** [EPIC-model/epic#370]
In order to calculate the reference potential energy (`peref`) the buoyancy must be ordered globally. This is not easily done with MPI. The parcel diagnostics in #368 does not take this into account at the moment and hence, the (reference) potential energy is wrong. This issue must also address the missing potential energy check in the unit test `test_mpi_parcel_diagnostics`.

**Comment by matt-frey** [comment]
Have a separate routine which is run optionally to get the proper reference potential energy.

**Comment by sjboeing** [comment]
@matt-frey: possibly remove
