### ISSUE TITLE
Unit tests: parcel initialization is not complete

### ISSUE THREAD

**Issue by gcorbin** [EPIC-model/epic#531]
In `unit_tests/test_ellipse_merge_symmetry.f90` the `parcel_setup` routine does not initialize buoyancy, humidity and vorticity. This can lead to SIGFPE: Floating-point exception - erroneous arithmetic operation. 

Adding 
```       
 parcels%buoyancy = 1.
 parcels%humidity = 1.
 parcels%vorticity = 0.
```

fixes this (not sure about the numbers, but does not seem to matter for the test).

**Comment by matt-frey** [comment]
@gcorbin Thank you for opening this issue.
