### ISSUE TITLE
PackagesNotFoundError

### ISSUE THREAD

**Issue by philrosenberg** [EPIC-model/epic#580]
When trying to create a new python environment following the docs I get the following error

`PackagesNotFoundError: The following packages are not available from current channels:`

 ` - python[version='3.12.0,3.9.10.*',build=hab00c5b_0_cpython]`

`Current channels:`

`  - https://conda.anaconda.org/cf-staging`
`  - https://conda.anaconda.org/conda-forge`
`  - defaults`

Sorry, I'm not a python user, so I'm not sure what the problem is

**Comment by matt-frey** [comment]
We recently updated the package list. This may have broken the setup. I will have a look.

**Comment by philrosenberg** [comment]
Fixed it - in the docs the command to create the new environment needs updating to say python=3.12.0 rather than python=3.9.10

**Comment by matt-frey** [comment]
Great, thanks! I will update this!
